/* Generated by wayland-scanner 1.11.0 */

#ifndef WESTON_SCREENSHOOTER_SERVER_PROTOCOL_H
#define WESTON_SCREENSHOOTER_SERVER_PROTOCOL_H

#include <stdint.h>
#include <stddef.h>
#include "wayland-server.h"

#ifdef  __cplusplus
extern "C" {
#endif

struct wl_client;
struct wl_resource;

/**
 * @page page_weston_screenshooter The weston_screenshooter protocol
 * @section page_ifaces_weston_screenshooter Interfaces
 * - @subpage page_iface_screenshooter - 
 */
struct screenshooter;
struct wl_buffer;
struct wl_output;

/**
 * @page page_iface_screenshooter screenshooter
 * @section page_iface_screenshooter_api API
 * See @ref iface_screenshooter.
 */
/**
 * @defgroup iface_screenshooter The screenshooter interface
 */
extern const struct wl_interface screenshooter_interface;

/**
 * @ingroup iface_screenshooter
 * @struct screenshooter_interface
 */
struct screenshooter_interface {
	/**
	 */
	void (*shoot)(struct wl_client *client,
		      struct wl_resource *resource,
		      struct wl_resource *output,
		      struct wl_resource *buffer);
};

#define SCREENSHOOTER_DONE	0

/**
 * @ingroup iface_screenshooter
 */
#define SCREENSHOOTER_DONE_SINCE_VERSION	1

/**
 * @ingroup iface_screenshooter
 * Sends an done event to the client owning the resource.
 * @param resource_ The client's resource
 */
static inline void
screenshooter_send_done(struct wl_resource *resource_)
{
	wl_resource_post_event(resource_, SCREENSHOOTER_DONE);
}

#ifdef  __cplusplus
}
#endif

#endif
