extern crate gcc;

fn main() {
    gcc::compile_library("libwayland-frontend.a", &[
        "src/global-enums.c",
        "src/global-types.c",
        "src/utils-chain.c",
        "src/utils-debug.c",
        "src/utils-environment.c",
        "src/utils-keyboard-state.c",
        "src/utils-list.c",
        "src/utils-log.c",
        "src/utils-store.c",
        "src/utils-time.c",
        "src/wayland-cache.c",
        "src/wayland-context.c",
        "src/wayland-engine.c",
        "src/wayland-facade.c",
        "src/wayland-gateway.c",
        "src/wayland-module.c",
        "src/wayland-output.c",
        "src/wayland-protocol-compositor.c",
        "src/wayland-protocol-data-device.c",
        "src/wayland-protocol-data-offer.c",
        "src/wayland-protocol-data-source.c",
        "src/wayland-protocol-device-manager.c",
        "src/wayland-protocol-keyboard.c",
        "src/wayland-protocol-output.c",
        "src/wayland-protocol-pointer.c",
        "src/wayland-protocol-region.c",
        "src/wayland-protocol-screenshooter.c",
        "src/wayland-protocol-seat.c",
        "src/wayland-protocol-shell-surface.c",
        "src/wayland-protocol-shell.c",
        "src/wayland-protocol-subcompositor.c",
        "src/wayland-protocol-subsurface.c",
        "src/wayland-protocol-surface.c",
        "src/wayland-protocol-xdg-popup.c",
        "src/wayland-protocol-xdg-shell.c",
        "src/wayland-protocol-xdg-surface.c",
        "src/wayland-region.c",
        "src/wayland-state.c",
        "src/wayland-surface.c",
        "src/wayland-transfer.c",
        "src/xdg-shell-protocol.c",
        "src/screenshooter-protocol.c",
    ]);

    println!("cargo:rustc-link-lib=dylib=wayland-server");
    println!("cargo:rustc-link-lib=dylib=xkbcommon");
}
